title       = "github"
baseURL     = "https://github-cli.tamnd.com/"
description = "A command line for GitHub, with no API token."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/github-cli"
